package br.com.unifacisa.projetointegrador.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClienteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClienteAllPropertiesEquals(Cliente expected, Cliente actual) {
        assertClienteAutoGeneratedPropertiesEquals(expected, actual);
        assertClienteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClienteAllUpdatablePropertiesEquals(Cliente expected, Cliente actual) {
        assertClienteUpdatableFieldsEquals(expected, actual);
        assertClienteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClienteAutoGeneratedPropertiesEquals(Cliente expected, Cliente actual) {
        assertThat(actual)
            .as("Verify Cliente auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClienteUpdatableFieldsEquals(Cliente expected, Cliente actual) {
        assertThat(actual)
            .as("Verify Cliente relevant properties")
            .satisfies(a -> assertThat(a.getTipoPessoa()).as("check tipoPessoa").isEqualTo(expected.getTipoPessoa()))
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getRazaoSocial()).as("check razaoSocial").isEqualTo(expected.getRazaoSocial()))
            .satisfies(a -> assertThat(a.getCpf()).as("check cpf").isEqualTo(expected.getCpf()))
            .satisfies(a -> assertThat(a.getCnpj()).as("check cnpj").isEqualTo(expected.getCnpj()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getTelefone()).as("check telefone").isEqualTo(expected.getTelefone()))
            .satisfies(a -> assertThat(a.getDataCadastro()).as("check dataCadastro").isEqualTo(expected.getDataCadastro()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClienteUpdatableRelationshipsEquals(Cliente expected, Cliente actual) {
        // empty method
    }
}
